"""Updates

Revision ID: 4161797f2baf
Revises: 
Create Date: 2023-06-08 15:01:47.604987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4161797f2baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
