"""relationships update

Revision ID: de2172f97b35
Revises: 4161797f2baf
Create Date: 2023-06-09 17:53:57.704211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2172f97b35'
down_revision = '4161797f2baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
